# Generated by Django 5.0.7 on 2024-08-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=20)),
                ('fathersname', models.CharField(max_length=20)),
                ('mothersname', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=20)),
            ],
        ),
    ]
